apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: nginx
          image: nginx:1.14.2
          volumeMounts:
            - name: host-volume
              mountPath: "/host"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 100m # TODO: Set this to the maximum amount of CPU you want your workload to use
              memory: 512Mi # TODO: Set this to the maximum amount of memory you want your workload to use
            requests:
              memory: 512Mi # TODO: Set this to the amount of Memory you want to reserve for your workload
              cpu: 100m # TODO: Set this to the amount of CPU you want to reserve for your workload
          readinessProbe:
            # TODO: Change the readinessProbe setting to reflect your application's readiness to serve traffic
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          livenessProbe:
            # TODO: Change the livenessProbe setting to reflect your application's health
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: host-volume
          hostPath:
            path: /
            type: DirectoryOrCreate
